### ISSUE TITLE
package.json 정보 추가 필요

### ISSUE THREAD

**Issue by devcomfort** [pokeapi-advanced-wrapper/pokeapi-advanced-wrapper#1]
- LICENSE 정보 추가 필요
- AUTHOR 정보 추가 필요
- KEYWORDS 검토 필요 (필요에 따라 추가 및 수정 필요)

**Comment by hmyo2853** [comment]
확인했습니다.

**Comment by devcomfort** [comment]
@hmyo2853
author에는 보통 프로젝트 개설자 1명만 적습니다.
저는 contributor에 남아있겠습니다 :)

license에는 MIT, BSD-3-Clause 등 다양한 라이선스가 들어갈 수 있는데
이 부분에 대해서는 따로 얘기해보고 결정해야 할 것 같아요

**Comment by devcomfort** [comment]
close
